docker:
  target:
    default:
      auto: true
      name: 编码风格检查
      deps:
        - clang-format-4.0
      allow_failure: false
      test:
        - ./code-format.sh --show-only --fail-on-diff -t $GITLAB_MASTER_COMMIT_SHA -b $GITLAB_COMMIT_SHA

    prebuild:
      name: 预编译
      auto: true
      allow_failure: false
      build:
        - apt-get install libaio-dev
        - cmake ./ -DCMAKE_BUILD_TYPE=Debug

    build:
      name: 编译
      auto: true
      allow_failure: true
      build:
        - make -j $(nproc)
    
    test:
      name: 测试
      auto: true
      allow_failure: true
      build:
        - make test