stages:
  - config
  - build
  - test

config:
  stage: config
  script:
    - apt-get update && apt-get install -y libaio-dev cmake
    - git submodule update --init --recursive
    - mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=Debug
  tags: 
    - shared

build:
  stage: build
  script:
    - cd build && make -j $(nproc)
  tags: 
    - shared

test:
  stage: test
  script:
    - cd build && make test
  tags: 
    - shared


